### ISSUE TITLE
`duplicate symbols` error occurs with other library

### ISSUE THREAD

**Issue by takasek** [BranchMetrics/Branch-iOS-SDK#110]
I found `_URL` duplicated with another library because of this commit. https://github.com/BranchMetrics/Branch-iOS-SDK/commit/e14d8ad8b9ae536f6d9661e1593d20a0e048c268
Variables used in Branch.m has too common names.
Can you add `static` or/and use much longer variable names?

**Comment by shortstuffsushi** [comment]
Hi @takasek, sorry about that. I'm not sure that was caused by the commit you're referencing, and unfortunately static would have the opposite of the desired effect (static variables are what cause this; instance variables won't). However, this will be addressed shortly.

I'm working on a Branch that would solve this problem entirely, but it's still a ways out, so I'll just make a quick fix for you for now.

**Comment by takasek** [comment]
Okay, thanks a lot.

Describing what I saw in detail;
I had tried to use v0.7.4 and found `duplicate symbols` on build phase, because another code also defines `_URL`.
And adding `static` to https://github.com/BranchMetrics/Branch-iOS-SDK/blob/master/Branch-SDK/Branch-SDK/Branch.m#L43 solves the error.

When I use v0.6.3, `duplicate symbols` doesn't occur.
https://github.com/BranchMetrics/Branch-iOS-SDK/blob/0.6.3/Branch-SDK/Branch-SDK/Branch.m
So I thought that the approach I wrote above might be an solution.

**Comment by shortstuffsushi** [comment]
Ah, indeed. I see what you're saying. Thanks for digging, I'll have a release out for you first thing in the morning.

**Comment by shortstuffsushi** [comment]
@takasek This should be available with the `0.7.5` release. Please let me know if you see any further issues.

**Comment by takasek** [comment]
I updated to `0.7.5` and made sure that the problem had been solved.
Thank you for your great rapid support :smile:
