### ISSUE TITLE
Distinguish deep links & new installs

### ISSUE THREAD

**Issue by bejo** [BranchMetrics/Branch-iOS-SDK#111]
I'd like to be able to tell, preferably within a deep link handler, whether a launch was triggered by a deep link on an existing app or launch options dict on a new install. Can you guys add this to your iOS API?

**Comment by shortstuffsushi** [comment]
Hey @bejo. We'll talk about this internally and get back to you. Just wanted to let you know we've seen this :)

**Comment by bejo** [comment]
Ok, thanks. (such a feature would be very useful for analytics)

**Comment by shortstuffsushi** [comment]
Hey @bejo. We've discussed this internally, and have added a backlog item to add the ability to do this. I'm not sure when you should be expecting it, but I will let you know once it has been made available. Thanks for the suggestion!

**Comment by bejo** [comment]
Awesome! Looking forward the new feature! :)

**Comment by shortstuffsushi** [comment]
Hey @bejo, you should have noticed a bunch of new parameters added in the past few days, including [`BRANCH_INIT_KEY_CLICKED_BRANCH_LINK`](https://github.com/BranchMetrics/Branch-iOS-SDK/blob/44d925ea1f8adcffce4549860ccecf8866ac8359/Branch-SDK/Branch-SDK/Branch.h#L89). You can find additional information about the parameters in [our quickstart docs](https://dev.branch.io/recipes/quickstart_guide/ios/#branch-provided-data-parameters).

These constants are all available in `0.7.8`, but the dictionary values themselves are available without requiring any SDK updates, since it was a backend change.

Let us know if you have any additional questions!
