### ISSUE TITLE
make warning instead of NSLog to notify App key is deprecated

### ISSUE THREAD

**Issue by nerd0geek1** [BranchMetrics/Branch-iOS-SDK#143]
I mention to Branch.m l.103 and l.108.
Some developers may overlook this message like me, so I think it is better to make warning to notify method deprecated.

**Comment by shortstuffsushi** [comment]
Hey @nerd0geek1, I think you're referring to lines [107](https://github.com/BranchMetrics/Branch-iOS-SDK/blob/3d906b181804d3f4918fac7bbfcea9cee7015956/Branch-SDK/Branch-SDK/Branch.m#L107) and [129](https://github.com/BranchMetrics/Branch-iOS-SDK/blob/3d906b181804d3f4918fac7bbfcea9cee7015956/Branch-SDK/Branch-SDK/Branch.m#L129) in the current version.

Unfortunately, since these methods themselves are not deprecated, there isn't really any way for us add compile-time warnings. I agree that just an NSLog isn't really ideal (perhaps we could make the message a little larger), but I don't know of a better way to prevent these earlier, or more notably.

For what it's worth, these two methods will remove support for app key with version 1.0.0 which is on the horizon, at which point you'll just get the "Branch Init Failed" message stating that you're missing your Branch Key.

If you have any other thoughts about how we may improve this, please let me know.
